/*
 * Copyright INAOS GmbH, Thalwil, 2012-2018. All rights reserved
 *
 * This software is the confidential and proprietary information of INAOS GmbH
 * ("Confidential Information"). You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with INAOS GmbH.
 */
#include <stdio.h>
#include <libinac/lib.h>

#define INA_ES_HELLO   (INA_ES_USER_DEFINED+1)
#define INA_ES_WORLD   (INA_ES_USER_DEFINED+2)
#define INA_ES_UNKNOWN (INA_ES_USER_DEFINED+3)

static const char* __ina_get_subject_a(int id)
{
    switch (id) {
        case INA_ES_HELLO:
            return "HELLO A";
        case INA_ES_WORLD:
            return "WORLD A";
        default:
            return "--";
    }
}

static const char* __ina_get_subject_b(int id)
{
    switch (id) {
        case INA_ES_HELLO:
            return "HELLO B";
        case INA_ES_WORLD:
            return "WORLD B";
        default:
            return "XX";
    }
}
INA_TEST_DATA(error);
INA_TEST(error, error_pack_rc)
{
    ina_rc_t rcc;
    ina_rc_t rc;
    INA_UNUSED(data);

    INA_TEST_ASSERT_SUCCEED(INA_SUCCESS);

    rcc =  0x8000000200058001;
    rc = INA_RC_PACK(INA_ES_ACCESS|INA_ERR_NOT_ALLOWED, 2);

    INA_TEST_MSG("verify INA_RC_PACK with %s", ina_err_strerror(rc));
    INA_TEST_ASSERT_EQUAL_UINT64(rcc, rc);
    INA_TEST_ASSERT_FAILED(rc);
;
    /* error indicator */
    INA_TEST_ASSERT_EQUAL_INT(1, INA_RC_EFLAG(rc));

    /* API version information */
    INA_TEST_ASSERT_EQUAL_INT(0, INA_RC_VER(rc));
    INA_TEST_ASSERT_EQUAL_INT(0,  INA_RC_REV(rc));

#undef INA_ERROR_VER
#undef INA_ERROR_REV
#define INA_ERROR_VER 2
#define INA_ERROR_REV 123
    rc = INA_RC_PACK(INA_ES_ACCESS|INA_ERR_NOT_ALLOWED, 2);
    INA_TEST_ASSERT_EQUAL_INT(2, INA_RC_VER(rc));
    INA_TEST_ASSERT_EQUAL_INT(123,  INA_RC_REV(rc));
#undef INA_ERROR_VER
#undef INA_ERROR_REV
#define INA_ERROR_VER INA_MAJOR_VERSION
#define INA_ERROR_REV INA_REVISION_HEX

    /* OS native error */
    INA_TEST_ASSERT_EQUAL_UINT(2, INA_RC_ERRNO(rc));

    /* code */
    INA_TEST_ASSERT_EQUAL_UINT64(INA_ERR_ALLOWED, INA_RC_CODE(rc));
    /* Adjective/Verb */
    INA_TEST_ASSERT_EQUAL_UINT64(5, INA_RC_ADJ(rc));

    /* Negate flag */
    INA_TEST_ASSERT_EQUAL_UINT(1, INA_RC_NFLAG(rc));

    /* subject */
    INA_TEST_ASSERT_EQUAL_INT(INA_ES_ACCESS, INA_RC_SUBJECT(rc));
    INA_TEST_ASSERT_NOT_EQUAL_INT(INA_ES_DEVICE, INA_RC_SUBJECT(rc));
    INA_TEST_ASSERT_NOT_EQUAL_INT(INA_ES_OPERATION, INA_RC_SUBJECT(rc));
    INA_TEST_ASSERT_EQUAL_INT(INA_ERR_NOT_ALLOWED, INA_RC_ERROR(rc));

    /* error message */
    INA_TEST_ASSERT_EQUAL_UINT64((INA_ES_ACCESS|INA_ERR_NOT_ALLOWED), INA_RC_ERRMSG(rc));
}

INA_TEST(error, error_same_as_errmsg)
{
    INA_UNUSED(data);

    INA_ERROR(INA_ERR_EMPTY);
    INA_TEST_ASSERT_EQUAL_INT(
            INA_RC_ERRMSG(ina_err_get_rc()),
            INA_RC_ERROR(INA_ERR_LAST_ERROR));

}

INA_TEST(error, get_set_rc)
{
    INA_UNUSED(data);

    INA_TEST_ASSERT_EQUAL_INT64(INA_RC_PACK(INA_ERR_FAILED, 0),
                                ina_err_set_rc(INA_RC_PACK(INA_ERR_FAILED, 0)));
    INA_TEST_ASSERT_EQUAL_INT64(INA_ERROR(INA_ERR_NOT_INITIALIZED),
                                ina_err_set_rc(INA_RC_PACK(INA_ERR_NOT_INITIALIZED, 0)));
}

INA_TEST(error, reset)
{
    INA_UNUSED(data);

    INA_TEST_ASSERT_FAILED(INA_ERROR(INA_ERR_NOT_INITIALIZED));
    INA_TEST_ASSERT_FAILED(ina_err_get_rc());
    INA_TEST_ASSERT_SUCCEED(ina_err_reset());
    INA_TEST_ASSERT_SUCCEED(ina_err_get_rc());
}

INA_TEST(error, strerror)
{
    INA_UNUSED(data);

    INA_ERROR(INA_ES_DEVICE | INA_ERR_IN_USE);
    INA_TEST_MSG("%s", ina_err_strerror(ina_err_get_rc()));
    INA_TEST_ASSERT_EQUAL_STR("DEVICE IN USE - 0x81060000003b0006 - error=1,ver=1,rev=6,os=0,neg=0,adj=59,subject=6,code=3866624,ubits=0x0", ina_err_strerror(
            ina_err_get_rc()));
}

INA_TEST(error, register_dict)
{
    INA_UNUSED(data);

    INA_TEST_ASSERT_NULL(ina_err_register_dict(__ina_get_subject_a));
    INA_ERROR(INA_ES_HELLO | INA_ERR_FAILED);
    INA_TEST_ASSERT_EQUAL_STR("HELLO A FAILED - 0x81060000002b0401 - error=1,ver=1,rev=6,os=0,neg=0,adj=43,subject=1025,code=2818048,ubits=0x0", ina_err_strerror(
            ina_err_get_rc()));
    INA_ERROR(INA_ES_WORLD | INA_ERR_NOT_FOUND);
    INA_TEST_ASSERT_EQUAL_STR("WORLD A NOT FOUND - 0x8106000000308402 - error=1,ver=1,rev=6,os=0,neg=1,adj=48,subject=1026,code=3145728,ubits=0x0", ina_err_strerror(
            ina_err_get_rc()));
    INA_ERROR(INA_ES_UNKNOWN | INA_ERR_NOT_FOUND);
    INA_TEST_ASSERT_EQUAL_STR("-- NOT FOUND - 0x8106000000308403 - error=1,ver=1,rev=6,os=0,neg=1,adj=48,subject=1027,code=3145728,ubits=0x0", ina_err_strerror(
            ina_err_get_rc()));
    INA_TEST_ASSERT_SAME(__ina_get_subject_a, ina_err_register_dict(__ina_get_subject_b));
    INA_ERROR(INA_ES_HELLO | INA_ERR_FAILED);
    INA_TEST_ASSERT_EQUAL_STR("HELLO B FAILED - 0x81060000002b0401 - error=1,ver=1,rev=6,os=0,neg=0,adj=43,subject=1025,code=2818048,ubits=0x0", ina_err_strerror(
            ina_err_get_rc()));
    INA_ERROR(INA_ES_WORLD | INA_ERR_NOT_FOUND);
    INA_TEST_ASSERT_EQUAL_STR("WORLD B NOT FOUND - 0x8106000000308402 - error=1,ver=1,rev=6,os=0,neg=1,adj=48,subject=1026,code=3145728,ubits=0x0", ina_err_strerror(
            ina_err_get_rc()));
    INA_ERROR(INA_ES_UNKNOWN | INA_ERR_NOT_FOUND);

    INA_TEST_ASSERT_EQUAL_STR("XX NOT FOUND - 0x8106000000308403 - error=1,ver=1,rev=6,os=0,neg=1,adj=48,subject=1027,code=3145728,ubits=0x0", ina_err_strerror(
            ina_err_get_rc()));
}

INA_TEST(error, ubits)
{
    INA_UNUSED(data);

    INA_ERROR(INA_ES_TIME | INA_ERR_EXCEEDED);
    INA_TEST_ASSERT_EQUAL_UINT(INA_ERR_EXCEEDED, INA_RC_ERROR(ina_err_get_rc()));
    INA_TEST_ASSERT_EQUAL_UINT(INA_ES_TIME, INA_RC_SUBJECT(ina_err_get_rc()));

    INA_TEST_ASSERT_EQUAL_INT(0, INA_RC_UBITS(ina_err_get_rc()));
    INA_TEST_ASSERT_EQUAL_UINT(INA_ERR_EXCEEDED, INA_RC_ERROR(ina_err_get_rc()));
    INA_TEST_ASSERT_EQUAL_UINT(INA_ES_TIME, INA_RC_SUBJECT(ina_err_get_rc()));
    INA_TEST_ASSERT_EQUAL_UINT((INA_ES_TIME|INA_ERR_EXCEEDED), INA_RC_ERRMSG(ina_err_get_rc()));

    INA_TEST_ASSERT_EQUAL_UINT(1, INA_RC_UBITS(ina_err_set_ubits(1)));
    INA_TEST_ASSERT_EQUAL_UINT(16, INA_RC_UBITS(ina_err_set_ubits(16)));
    INA_TEST_ASSERT_EQUAL_UINT(255, INA_RC_UBITS(ina_err_set_ubits(255)));
    INA_TEST_ASSERT_EQUAL_UINT(INA_ERR_EXCEEDED, INA_RC_ERROR(ina_err_get_rc()));
    INA_TEST_ASSERT_EQUAL_UINT(INA_ES_TIME, INA_RC_SUBJECT(ina_err_get_rc()));
    INA_TEST_ASSERT_EQUAL_UINT((INA_ES_TIME|INA_ERR_EXCEEDED), INA_RC_ERRMSG(ina_err_get_rc()));
}

INA_TEST(error, verify_adj)
{
    INA_UNUSED(data);

    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_A, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ACK, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ACTIVE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ALIGNED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ALLOWED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ASSIGNED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ATTACHED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ATTEMPTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_AUTHORIZED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_AVAILABLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_BAD, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_BLOCKED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_BROKEN, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_BUILT, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_BUSY, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_CLOSED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_COMPILED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_COMPLETE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_CONFLICTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_CONNECTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_CONSTRUCTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_CREATED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_DEFINED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_DENIED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_DESTRUCTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_DETACHED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_DETECTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_DOWN, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_DOWNLOADED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_EMPTY, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ENHANCED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ENOUGH, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_EXCEEDED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_EXCHANGED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_EXECUTABLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_EXISTS, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_EXPIRED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_EXTENDED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_FAILED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_FALSE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_FATAL, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_FORBIDDEN, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_FORMATTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_FOUND, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_FULL, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_GONE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_GOOD, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_HALTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_HOLD, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_IDLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ILLEGAL, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_IMPLEMENTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_IN_PROGRESS, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_IN_USE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_INITIALIZED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_INSTALLED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_INTERRUPTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_KNOWN, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_LINKED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_LOADED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_LOCAL, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_LOCKED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_LOOPED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_LOST, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_MISSING, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_MOUNTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_NEEDED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_NO, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_NO_SUCH, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_OFF, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ON, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ONLINE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_OPEN, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_ORDERED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_OUT_OF, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_OVERFLOW, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_PADDED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_PERMITTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_PROCESSABLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_PROVIDED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_REACHABLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_READABLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RECEIVED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_REFUSED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_REGISTERED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_REJECTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RELEASED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_REMOTE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RENDERABLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RESERVED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RESET, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RESPONDING, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RETRIED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RIGHT, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RUNNING, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_SENT, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_SPECIFIED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_STALLED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_STOPPED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_SUCEEDED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_SUITABLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_SUPPORTED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_SYNCHRONIZED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TERMINATED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_THROWN, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TIMED_OUT, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TOO_COMPLEX, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TOO_FEW, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TOO_LARGE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TOO_LONG, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TOO_MANY, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TOO_MUCH, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TOO_SIMPLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TOO_SMALL, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TRIGGERED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TRUE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_UNIQUE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_UP, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_UPDATED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_UPGRADED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_UPLOADED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_USED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_VALID, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_WORKING, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_WRITABLE, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_WRONG, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_END_OF, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_RESOLVED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_MATCH, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_TRY_AGAIN, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_PARSED, INA_ES_NONE)));
    INA_TEST_ASSERT_NOT_NULL(ina_err_strerror(INA_RC_PACK(INA_ERR_CHANGED, INA_ES_NONE)));
}