#ifndef AXTLS_CONFIG_H
#define AXTLS_CONFIG_H

#define CONFIG_SSL_FULL_MODE 1
#define CONFIG_SSL_PROT_MEDIUM 1

#define CONFIG_X509_MAX_CA_CERTS 150
#define CONFIG_SSL_MAX_CERTS 3
#define CONFIG_SSL_EXPIRY_TIME 24 

/* #define CONFIG_SSL_X509_CERT_LOCATION ""*/
#define CONFIG_SSL_GENERATE_X509_CERT 1
#define CONFIG_SSL_X509_COMMON_NAME "www.inaos.ch"
#define CONFIG_SSL_X509_ORGANIZATION_NAME "INAOS GmbH"
#define CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME "IT"

#define CONFIG_SSL_USE_DEFAULT_KEY 1
#define CONFIG_SSL_PRIVATE_KEY_LOCATION ""
#define CONFIG_SSL_PRIVATE_KEY_PASSWORD ""

#endif