/*
 * Copyright 2014-2020 INAOS GmbH, Thalwil
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef _LIBINAC_COMPRESSION_H_
#define _LIBINAC_COMPRESSION_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <libinac/lib.h>

/*
 * TODO: this should go into the manual instead of the header file
 *
 * How to use the module:
 *
 * 1. Create a new compression state, type (e.g. DEFLATE or LZ4) is mandatory
 *    the size of the source buffer is configurable - default is 4MB
 * 2. Once the state has been created you call
 *    ina_compression_get_destination_len() to obtain the length of the
 *    destination buffer that you have to manage/allocate
 * 3. Then call ina_compression_compress_chunk() until your stream is EOF
 * 4. Same goes for decompression but instead you call
 *    ina_compression_decompress_chunk()
 *
 */

/* Compression type */
typedef enum ina_compression_type_e {
    INA_COMPRESSION_TYPE_DEFLATE,
    INA_COMPRESSION_TYPE_DEFLATE_RAW,
    INA_COMPRESSION_TYPE_LZ4,
    INA_COMPRESSION_TYPE_LZ4HC,
} ina_compression_type_t;

/* Compression mode */
typedef enum ina_compression_mode_e {
    INA_COMPRESSION_MODE_TRUSTED_FAST,
    INA_COMPRESSION_MODE_TRUSTED_SAFE,
} ina_compression_mode_t;

/* Opaque compression state */
typedef struct ina_compression_state_s ina_compression_state_t;

/*
 * Create and initialize a new compression state for further use.
 *
 * Parameters
 *  state   Where to store pointer to state
 *  type    Type of compression
 *  mode    Compression mode
 *
 * Return
 *  INA_SUCCESS if all went well
 */
INA_API(ina_rc_t) ina_compression_new(ina_compression_state_t **state,
                                      ina_compression_type_t type,
                                      ina_compression_mode_t mode);

/*
 * Create and initialize, a new compression state for further use, using
 * a memory pool.
 *
 * Parameters
 *  state   Where to store pointer to state
 *  type    Type of compression
 *  mode    Compression mode
 *  pool    Memory pool
 *
 * Return
 *  INA_SUCCESS if all went well
 */
INA_API(ina_rc_t) ina_compression_new_using_pool(ina_compression_state_t **state,
                                                 ina_compression_type_t type,
                                                 ina_compression_mode_t mode,
                                                 ina_mempool_t *pool);
/*
 * Reset compression state.
 *
 * Parameters
 *  state   State to reset
 *
 * Return
 *  INA_SUCCESS
 */
INA_API(ina_rc_t) ina_compression_reset(ina_compression_state_t *state);

/*
 * Destroy a compression state.
 *
 * Parameters
 *  state  Compression state to free
 *
 * Return
 *  INA_SUCCESS if all went well
 */
INA_API(void) ina_compression_free(ina_compression_state_t **state);

/*
 * Conservative upper bound on the amount of data that could be generated by
 * calling ina_compression_compress_chunk.
 *
 * Parameters
 *  state    Compression state
 *  src_len  Source size in bytes
 *  dst_len  Where to store destination size in bytes
 *
 * Return
 *  INA_SUCCESS if all went well
 *
 * TODO: Implementation
 */
INA_API(ina_rc_t) ina_compression_get_destination_len(
                                                ina_compression_state_t *state,
                                                int src_len,
                                                int *dst_len);
/*
 * Compress a chunk of data.
 *
 * Parameters
 *  state      Compression state
 *  src        Source data (uncompressed)
 *  src_len    Source data length in bytes
 *  dst        Output buffer
 *  dst_len    Output buffer size in bytes
 *  wrote_len  Where to store number of bytes written to dst
 *  read_len   Where to store number of bytes read from src
 *  more       Flag to indicates if more data must be compressed. Use eighter
 *             INA_YES or INA_NO.
 *
 * Return
 *  INA_SUCCESS if all went well
 */
INA_API(ina_rc_t) ina_compression_compress_chunk(ina_compression_state_t *state,
                                                 const unsigned char *src,
                                                 int src_len,
                                                 unsigned char *dst,
                                                 int dst_len,
                                                 int *wrote_len,
                                                 int *read_len,
                                                 int more);
/*
 * Decompress a chunk of data.
 *
 * Parameters
 *  state      Compression state
 *  src        Source data (compressed)
 *  src_len    Source data length in bytes
 *  dst        Output buffer
 *  dst_len    Output buffer size in bytes
 *  wrote_len  Where to store number of bytes written to dst
 *  read_len   Where to store number od bytes read from src
 *  more       Flag to indicates if more data must be compressed. Use either
 *             NA_YES or INA_NO.
 *
 * Return
 *  INA_SUCCESS if all went well
 */
INA_API(ina_rc_t) ina_compression_decompress_chunk(ina_compression_state_t *state,
                                                   const unsigned char *src,
                                                   int src_len,
                                                   unsigned char *dst,
                                                   int dst_len,
                                                   int *wrote_len,
                                                   int *read_len,
                                                   int more);

#ifdef __cplusplus
}
#endif

#endif
